---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family|lower }}.yaml"
  when: ansible_os_family == 'RedHat'

- name: install required packages
  become: yes
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"

- include_tasks: sshd.yaml

- name: ensure journalctl will not eat whole disk
  command: sed -i -e 's,#SystemMaxUse.*,SystemMaxUse=1G,' /etc/systemd/journald.conf
  notify:
    - restart journald
