---
- name: firewall service
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: sshd service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: set sshd config
  command: sed -i -e 's,AllowTcpForwarding.*,AllowTcpForwarding yes,' /etc/ssh/sshd_config
  notify:
    - restart sshd
