---
- name: firewall daemon
  package:
    name: firewalld
    state: installed

- name: firewall service
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: sshd daemon
  package:
    name: openssh-server
    state: installed

- name: sshd service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: set sshd config
  command: sed -i -e 's,AllowTcpForwarding.*,AllowTcpForwarding yes,' /etc/ssh/sshd_config
  notify:
    - restart sshd
