---
- name: Provision DNS infrastructure
  hosts: localhost
  environment:
    OS_CLOUD: "{{ lookup('env', 'OS_CLOUD') | default(cloud_name) }}"
  tasks:
    - include_role:
        name: app_cluster
        tasks_from: unprovision
