---
# Create KeyPair and save it locally
- name: Create KeyPair
  os_keypair:
    state: present
    name: "{{ keypair_name }}"
  register: keypair_output

- name: Save private key
  copy:
    dest: "{{ keypair_private_key_dest }}"
    content: "{{ keypair_output['key']['private_key'] }}"
    mode: 0600
  when:
    - keypair_output is defined and keypair_output['key']['private_key'] is defined
    - keypair_output.changed
