---
- name: evaluate groups
  import_playbook: ../init/evaluate_groups.yml

# Need to be executed from the bastion host, since it's
# not possible to update DNS servers without direct access to them (they do not have public IPs)
- name: Register cluster instances in the DNS
  hosts: bastions
  environment:
    OS_CLOUD: "{{ cloud_name }}"
  tasks:
    - include_role:
        name: app_cluster
        tasks_from: prepare_dns

- name: Register cluster instances in the DNS
  hosts: bastions
  environment:
    OS_CLOUD: "{{ cloud_name }}"
  tasks:
    - include_role:
        name: app_cluster
        tasks_from: depopulate_dns
