---
- name: Destroy VPC
  hosts: localhost
  environment:
    OS_CLOUD: "{{ cloud_name }}"
  tasks:
    - include_role:
        name: vpc
        tasks_from: destroy
    - include_role:
        name: keypair
        tasks_from: destroy
      vars:
        keypair_name: "{{ common_keypair_name }}"
