---
- name: Destroy VPC
  hosts: localhost
  tasks:
    - include_role:
        name: vpc
        tasks_from: destroy
    - include_role:
        name: keypair
        tasks_from: destroy
      vars:
        keypair_name: "{{ common_keypair_name }}"
