---
- name: Provision DNS infrastructure
  hosts: localhost
  environment:
    OS_CLOUD: "{{ cloud_name }}"
  tasks:
    - include_role:
        name: dns
        tasks_from: provision

- name: register RHE
  hosts: all
  become: true
  tasks:
    - name: Install Satellite CA certificate
      yum:
        name: "http://{{ rhsm_satellite }}/pub/katello-ca-consumer-latest.noarch.rpm"
        state: present
      when: rhsm_satellite | default

    - name: Subscribe to Satellite with activation key and auto-attach
      redhat_subscription:
        autosubscribe: true
        server_hostname: "{{ rhsm_satellite | default(None) }}"
        org_id: "{{ rhsm_org_id | default(None) }}"
        activationkey: "{{ rhsm_activation_key }}"
      when: rhsm_activation_key | default

    - name: Subscribe to RHSM and auto-attach
      redhat_subscription:
        username: "{{ rhn_username | default(None) }}"
        password: "{{ rhn_password | default(None) }}"
        autosubscribe: true
        server_hostname: "{{ rhsm_satellite | default(None) }}"
        org_id: "{{ rhsm_org_id | default(None) }}"
      when: rhn_username|default and rhn_password|default and rhn_pool|default == ""

    - name: Subscribe to RHSM and attach a pool
      redhat_subscription:
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool_ids: ["{{ rhn_pool }}"]
        server_hostname: "{{ rhsm_satellite|default(None) }}"
        org_id: "{{ rhsm_org_id|default(None) }}"
      when: rhn_username|default and rhn_password|default and rhn_pool|default

- name: Prepare Bind
  hosts: bind
  become: true
  tasks:
    - include_role:
        name: dns
        tasks_from: bind.yml

- name: Provision master
  hosts: masters
  become: true
  tasks:
    - include_role:
        name: dns
        tasks_from: masters.yml

- name: Provision slaves
  hosts: slaves
  become: true
  tasks:
    - include_role:
        name: dns
        tasks_from: slaves.yml
