---
- name: debug ns records
  debug:
    var: openshift_openstack_dns_records

- name: python-dns daemon
  become: yes
  package:
    name: python-dns
    state: installed

- name: "Add DNS A records"
  nsupdate:
    key_name: "{{ item.0.key_name }}"
    key_secret: "{{ item.0.key_secret }}"
    key_algorithm: "{{ item.0.key_algorithm }}"
    server: "{{ item.0.server }}"
    zone: "{{ item.0.zone }}"
    record: "{{ item.1.hostname }}"
    value: "{{ item.1.ip }}"
    type: "{{ item.1.type }}"
    state: absent
  with_subelements:
    - "{{ openstack_dns_records | default([]) }}"
    - entries
  register: nsupdate_add_result
  until: nsupdate_add_result is succeeded
  retries: 10
  delay: 1
