---
# On RHEL7 this is python-dns.  On F25 it's python2-dns
- name: install python DNS package
  package:
    name: python2-dns
    state: installed
  when: (ansible_distribution == "Fedora")

- name: install python DNS package
  package:
    name: python-dns
    state: installed
  when: (ansible_distribution == "RHEL" or ansible_distribution == "CentOS")

- name: named master zone configuration file(s)
  template:
    src: templates/bind/zones.conf-master.j2
    dest: /etc/named/zones.conf
  notify:
    - restart named

- name: set zone update key
  template:
    src: templates/bind/update.key.j2
    dest: /etc/named/update.key
  notify:
    - restart named

- name: named master zones configuration file(s)
  template:
    src: templates/bind/zone.db.j2
    dest: "{{ '/var/named/dynamic/' + item + '.db' }}"
  with_items: "{{ zones }}"
  tags:
    - zonedata
  notify:
    - restart named

- name: named master zone configuration file(s)
  template:
    src: templates/bind/rev.zone.j2
    dest: "{{ '/var/named/dynamic/' + item + '.db' }}"
  with_items: "{{ reverse_zones }}"
  tags:
    - zonedata
  notify:
    - restart named
