---
- name: Create Network
  os_network:
    name: "{{ network_name }}"
    state: present

- name: Create default subnet
  os_subnet:
    name: "{{ default_subnet_name }}"
    state: present
    network_name: "{{ network_name }}"
    cidr: "{{ default_subnet_cidr }}"
    dns_nameservers: "{{ default_dns_servers }}"

# upstream expects enable_snat to be defaulted to true, but in OTC it is not that
# therefore it is required to enable snat manually later or use heat
- name: Create Router
  os_router:
    name: "{{ router_name }}"
    state: present
    network: "{{ external_network_name }}"
    enable_snat: True
    interfaces:
      - net: "{{ network_name }}"
        subnet: "{{ default_subnet_name }}"
