---
- include: "{{ net_task }}.yaml"
  loop_control:
    loop_var: net_task
  with_items: "{{ net_task_manager }}"

- name: Assert that elements were registered
  assert:
    that:
      - net_network is defined
      - net_subnet is defined
      - net_router is defined

- name: debug
  debug:
    var: net_router
    
- name: Assert that SNAT is enabled on the router
  assert:
    that:
      - net_router.router.external_gateway_info.enable_snat
