---
- name: Create default subnet
  os_subnet:
    name: "{{ subnet_name }}"
    state: "{{ module_state }}"
    network_name: "{{ network_name }}"
    cidr: "{{ subnet_cidr }}"
    dns_nameservers: "{{ subnet_dns_servers | default(omit) }}"
  register: net_subnet
  when: module_state != 'absent'

- name: Delete default subnet
  os_subnet:
    name: "{{ subnet_name }}"
    state: "{{ module_state }}"
  when: module_state == 'absent'
